-- COUNT RETORNA NUMERO DE LINHAS DE ACORDO COM A CONDIÇÃO
-- SELECT COUNT(coluna) FROM TABELA

SELECT COUNT(DISTINCT Title)
FROM Person.Person

-- DESAFIOS
/* 01 - EU QUERO SABER QUANTOS PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA DE PRODUTOS PRODUCTION.PRODUCT*/

SELECT COUNT(*)
FROM Production.Product

/* 02 - EU QUERO SABER QUANTOS TAMANHOS DE PRODUTOS TEMOS CADASTRADOS EM NOSSA TABELA PRODUCTION.PRODUCT*/

SELECT COUNT(Size)
FROM Production.Product

/* 03 - EU QUERO SABER QUANTOS TAMANHOS DIFERENTES DE PRODUTOS EU TENHO CADASTRADOS EM NOSSA TABELA PRODUCTION.PRODUCT*/

SELECT COUNT(DISTINCT Size)
FROM Production.Product