-- ORDER BY ORDENA RESULTADOS
-- SELECT * FROM TABLE ORDER BY ASC/DESC

SELECT *
FROM Person.Person 
ORDER BY FirstName ASC, LastName DESC

-- DESAFIOS

/* 01 OBTER O PRODUCTID DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO DO MAIS CARO PARA O MAIS BARATO*/

SELECT TOP 10 ProductID 
FROM Production.Product
ORDER BY ListPrice DESC

/* 02 OBTER O NOME E NUMERO DO PRODUTO, DOS PRODUTOS QUE TEM O PRODUCTID ENTRE 1~4*/

SELECT TOP 4 Name, ProductNumber 
FROM Production.Product
ORDER BY PRODUCTID ASC

