-- ORDER BY ORDENA RESULTADOS
-- SELECT * FROM TABLE ORDER BY ASC/DESC

SELECT *
FROM Person.Person 
ORDER BY FirstName ASC, LastName DESC

-- DESAFIOS

/* 01 OBTER O PRODUCTID DOS 10 PRODUTOS MAIS CAROS CADASTRADOS NO SISTEMA, LISTANDO DO MAIS CARO PARA O MAIS BARATO*/

SELECT TOP 10 ProductID 
FROM Production.Product
ORDER BY ListPrice DESC

