-- DESAFIOS FUNDAMENTOS SQL
-----------------------------------
/*
	1 - QUANTOS PRODUTOS TEMOS CADASTRADO NO SISTEMA QUE CUSTAM MAIS DE 1500 DOLARES
*/

SELECT COUNT(ListPrice)
FROM Production.Product
WHERE ListPrice > 1500

/*
	2 - QUANTAS PESSOAS TEM O SOBRENOME QUE INICIA COM A LETRA P
*/

SELECT COUNT(LastName)
FROM Person.Person
WHERE LastName LIKE 'P%'

/*
	3 - EM QUANTAS CIDADES ESTÃO CADASTRADOS OS NOSSOS CLIENTES?
*/

SELECT  COUNT(DISTINCT(City)) 
FROM Person.Address


/*
	4 - QUAIS SÃO AS CIDADES UNICAS QUE SÃO CADASTRADOS EM NOSSO SISTEMA?
*/

SELECT DISTINCT(CITY)
FROM Person.Address


/*
	5 - QUANTOS PRODUTOS VERMELHOS TEM PREÇO ENTRE 500 E 1000 DOLARES?
*/

SELECT COUNT(ProductID)
FROM Production.Product
WHERE Color = 'RED' 
AND ListPrice BETWEEN 500 AND 1000

/*
	6 -  QUANTOS PRODUTOS CADASTRADOS TEM A PALAVRA 'ROAD' NO NOME DELES?
*/

SELECT COUNT(*)
FROM Production.Product
WHERE NAME LIKE '%ROAD%'

