-- MIN MAX SUN AVG
/*
	FUNÇÕES DE AGREGAÇÃO BASICAMENTE AGREGAM OU COMBINAM DADOS DE UMA TABELA EM 1 RESULTADO SÓ
*/

SELECT TOP 10 SUM(LineTotal) AS 'SOMA' -- RETORNA A SOMA DA COLUNA SELECIONADA
FROM Sales.SalesOrderDetail

SELECT TOP 10 MIN(LineTotal) -- RETORNA O MENOR VALOR SELECIONADO
FROM Sales.SalesOrderDetail

SELECT TOP 10 MAX(LineTotal) -- RETORNA O MAIR VALOR SELECIONADO
FROM Sales.SalesOrderDetail

SELECT TOP 10 AVG(LineTotal) -- RETORNA A MÉDIA DOS VALORES SELECIONADOS
FROM Sales.SalesOrderDetail

