-- HAVING

/*
	ELE É BASICAMENTE USADO MUITO EM JUNÇÃO COM O GROUP BY PARA FILTRAR RESULTADOS DE UM AGRUPAMENTO	
	ELE É BASICAME O WHERE DO GROUP BY

	SINTAXE:
		SELECT COLUMN, FUNÇÃOAGREGAÇÃO(COLUNA)
		FROM TABLE
		GROUP BY COLUMN
		HAVING CONDICÃO
	
	A GRANDE DIFERENÇA DO HAVING E O WHERE:
	É QUE O GROUP BY É APLICADO DEPOIS QUE OS DADOS JÁ FORAM AGRUPADOS, 
	ENQUANTO O WHERE É APLICADO ANTES DOS DADOS SEREM AGRUPADOS.
*/

-- VAMOS DIZER QUE QUEREMOS SABER QUAIS NOMES NO SISTEMA TEM A OCORRENCIA MAIOR QUE 10 VEZES

SELECT FIRSTNAME, COUNT(FIRSTNAME) AS 'QUANTIDADE'
FROM Person.Person
GROUP BY FirstName
HAVING COUNT(FirstName) > 10


-- POR EXEMPLO QUEREMOS SABE QUAIS PRODUTOS QUE NO TOTAL DE VENDAS ESTÃO ENTRE 162K E 500K

SELECT PRODUCTID, SUM(LINETOTAL) AS 'TOTAL'
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN 162000 AND 500000

-- VAMOS DIZER QUE QUEREMOS SABER QUAIS NOMES NO SISTEMA TEM A OCORRENCIA MAIOR QUE 10 VEZES, POREM SOMENTE ONDE O TITULO É 'MR.'

SELECT FIRSTNAME, COUNT(FIRSTNAME) AS 'QUANTIDADE'
FROM Person.Person
WHERE Title LIKE 'MR.'
GROUP BY FirstName
HAVING COUNT(FirstName) > 10


-- DESAFIOS 

/*
	1 - ESTAMOS QUERENDO INDENTIFICAR AS PROVINCIAS(STATEPROVIDENCEID) COM O MAIOR NUMERO DE CADASTROS NO NOSSO SISTEMA, 
	ENTÃO É PRECISO ENCONTRAR QUAIS PROVINCIAS(STATEPROVIDENCEID) ESTÃO REGISTRADAS NO BANCO DE DADOS MAIS DE 1000 VEZES
*/

SELECT StateProvinceID, COUNT(StateProvinceID) AS 'TOTAL'
FROM Person.Address
GROUP BY StateProvinceID
HAVING COUNT(StateProvinceID) > 1000


/*
	2 - SENDO QUE SE TRATA DE UMA MULTINACIONAL OS GERENTES QUEREM SABER QUAIS PRODUTOS(PRODUCTID) NÃO ESTÃO TRAZENDO EM 
	MEDIA NO MINIMO 1 MILHAO EM TOTAL DE VENDAS(LINETOTAL)
*/

SELECT ProductID, AVG(LineTotal)
FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING COUNT(LineTotal) < 1000000








