-- TIPOS DE JOINS

CREATE DATABASE TESTE_JOIN

USE TESTE_JOIN

/*LEFT*/
CREATE TABLE A( 
	ID INTEGER IDENTITY(1,1)NOT NULL,
	NOME VARCHAR(50) NOT NULL
)

/*RIGHT*/
CREATE TABLE B(
	ID INTEGER IDENTITY(1,1)NOT NULL,
	NOME VARCHAR(50) NOT NULL
)


/*
	DADOS
	TABLE A(ROBO,MACACO,SAMURAI,MONITOR)
	TABLE B(ESPADA, ROBO,MARIO,SAMURAI)
*/

SELECT * FROM A
SELECT * FROM B




DROP DATABASE TESTE_JOIN



-- INNER JOIN
/*
	INNER JOIN RETORNA APENAS OS RESULTADOS QUE CORRESPONDEM(EXISTEM)TANTO NA TABELA A COMO NA TABELA B
*/

SELECT * FROM A
INNER JOIN B
ON A.NOME = B.NOME


-- FULL OUTER JOIN
/*
	FULL OUTER JOIN RETORNA UM CONJUNTO DE TODOS OS REGISTROS CORRESPONDENTES DA TABELA A E TABELA B QUANDO SAO IGUAIS.
	E ALEM DISSO SE NÃO HOUVER VALORES CORRESPONDENTES, ELE SIMPLISMENTE IRÁ PRENCHER ESSE LADO COMO NULL
*/

SELECT * FROM A
FULL OUTER JOIN B
ON A.NOME = B.NOME

-- LEFT OUTER JOIN
/*
	LEFT OUTER JOIN RETORNA UM CONJUNTO DE TODOS OS REGISTROS DA TABELA A, E ALEM DISSO, OS REGISTROS CORRESPONDENTES
	(QUANDO DISPONIVEIS)NA TABELA B. SE NÃO HOUVER RESGITROS CORRESPONDENTES ELE SIMPLESMENTE VAI PRENCHER COMO NULL
*/

SELECT * FROM A
LEFT OUTER JOIN B
ON B.NOME = A.NOME

-- RIGHT OUTER JOIN
/*
	RIGHT OUTER JOIN RETORNA UM CONJUNTO DE TODOS OS REGISTROS DA TABELA B, E ALEM DISSO, OS REGISTROS CORRESPONDENTES
	(QUANDO DISPONIVEIS)NA TABELA A. SE NÃO HOUVER RESGITROS CORRESPONDENTES ELE SIMPLESMENTE VAI PRENCHER COMO NULL
*/

SELECT * FROM B
LEFT OUTER JOIN A
ON A.NOME = B.NOME


	
