-- OUTER JOIN OU LEFT OUTER JOIN OU LEFT JOIN

USE AdventureWorks2017

-- QUERO DESCOBRIR QUAIS PESSOAS TEM UM CARTÃO DE CREDITO REGISTRADO

SELECT *
FROM Person.Person AS PP
INNER JOIN Sales.PersonCreditCard AS PC
ON PP.BusinessEntityID = PC.BusinessEntityID
-- INNER JOIN: 19.118 LINHAS

SELECT *
FROM Person.Person AS PP
LEFT JOIN Sales.PersonCreditCard AS PC
ON PP.BusinessEntityID = PC.BusinessEntityID
WHERE PC.BusinessEntityID IS NULL -- COM ESSA LINHA VERIFICA QUAIS PESSOAS NAO TEM CARTÃO DE CREDITO
-- LEFT JOIN: 19.972 LINHAS

SELECT 19972 - 19118
-- RESULTADO 854 PESSOAS NAO TEM CARTÕES DE CREDITO
