-- SELF JOIN
-- AGRUPAR DADOS DENTRO DA MESMA TABELA(SOMENTE COM APELIDO)
/*
SELECT NOME_COLUNA
FROM TABELA_A, TABELA_B
WHERE CONDICAO
*/



SELECT A.ContactName,A.REGION, B.ContactName, B.REGION
FROM CUSTOMERS A, Customers B
WHERE A.REGION = B.REGION





SELECT A.FirstName, A.HireDate ,B.FirstName, B.HireDate
FROM Employees A, Employees B
WHERE DATEPART(YEAR,A.HireDate) = DATEPART(YEAR,B.HireDate)

